### ISSUE TITLE
[feature request] Add "move all files in current note" option & export all unused files

### ISSUE THREAD

**Issue by tracure1337** [JYC333/obsidian-attachment-name-formatting#1]
[feature request] 

>Add "move all files from current note" option

This would allow to easily gather all note related files/attachments and move them to another vault or quickly share them.

Optionally allow for autodeletion after export/move.

>export all unused files

Allow export of all attachments which are not used in any notes.
This would help tremendously with cleanup.

Thank you for this great plugin.

**Comment by JYC333** [comment]
Sorry for the late reply.

Thanks for your feature proposal, and I'm glad to hear that this plugin helps you.

The feature is updated now, you can have a try.

Welcome to bring up anything back to me!

**Comment by JYC333** [comment]
I'll close it this week if no more comments comming.

**Comment by tracure1337** [comment]
@JYC333  Thanks. Just checked in today.

Will try it out later today!  Thanks so much!
