### ISSUE TITLE
Feature: Add a reference list of what variables to use to specify format

### ISSUE THREAD

**Issue by magi44ken** [JYC333/obsidian-attachment-name-formatting#10]
Currently, there is no reference list or document that list the variables that we can use to specify the format. I also google search and here in Github and can't find it. Can you add a reference list in the settings of what variables you can use? Thanks.

**Comment by JYC333** [comment]
Hi, thanks for using this plugin!

What do you mean about the variables that you can use to specify the format? Do you mean how to change the attachment format for different types of attachments? If it is, I update the readme and the description in the setting. If it's something else, could you please explain it a little bit more?

**Comment by JYC333** [comment]
Update the README, hope the updated one can answer your question
