### ISSUE TITLE
Feature: Rename all notes within a folder or vault.

### ISSUE THREAD

**Issue by magi44ken** [JYC333/obsidian-attachment-name-formatting#11]
I suggest three related features here.

1. Add a feature to allow user to rename the attachments for all the notes within a folder and all subfolders. 

2. Another feature to rename the attachments within vault.

3. Log

Also important to save a log that contain any attachments that cannot rename successfully such as the known bugs. When it is finish renaming all the notes, it will automatically show the log how many attachments can't be rename unsuccessful and the link to the note and attachment.

The log layout might look something this.

Note Title 1 (Bold)

- Attachment name 1
- Attachment name 2

Note Title 2 (Bold)

- Attachment name 1
- Attachment name 2

**Comment by JYC333** [comment]
Sorry for the late reply, now the feature is updated in 1.6.0.
