### ISSUE TITLE
Feature: Option to Disable renaming of pdf

### ISSUE THREAD

**Issue by JFinnTeacher** [JYC333/obsidian-attachment-name-formatting#12]
When Adding pdf files to a document I would like to option to retain the name of the pdf rather than renaming them. This would allow for easier management of notes with multiple pdf files embedded.

Could this be set either in option or through YAML?

**Comment by JYC333** [comment]
Sorry for the late reply, now it's added in 1.5.0 now. You can now disable renaming for each type of attachment.
