### ISSUE TITLE
Unable to rename automatically

### ISSUE THREAD

**Issue by chenxin0397** [JYC333/obsidian-attachment-name-formatting#13]
Hi, when I first installed this plugin in July, all open notes were automatically renamed with the filename of the attachment. After a recent update to 1.4.4, it was found that the function of automatically updating filenames is no longer available. What's the situation now?

**Comment by chenxin0397** [comment]
I looked again and it still works, but filenames like
 [[../../900-tools/zzz-resources/Pasted image 20220913225043.png]] didn't change, changed to
 [[900-tools/zzz-resources/Pasted image 20220913225043.png]]
 is fine

**Comment by JYC333** [comment]
The plugin will update the filenames automatically when you make some changes to the note. Could you try for the pasted image again?

**Comment by chenxin0397** [comment]
It doesn't seem to work, changing the file name and the attachment name will not change it.

**Comment by chenxin0397** [comment]
It doesn't seem to work, changing the file name and the attachment name will not change it.
Unless I manually delete the ../ at the beginning of the []() path

**Comment by JYC333** [comment]
Fixed in 1.4.5 now. It will recognize "../" in the file path, but it will remove "../".
