### ISSUE TITLE
Feature request: Ignore certain file types

### ISSUE THREAD

**Issue by vguillet** [JYC333/obsidian-attachment-name-formatting#16]
Love the extension so far, I wish there was a way however to exclude certain file types from being renamed. I am mainly thinking about svg for example. I create a lot of diagrams using draw.io, which I consider less as part of a note, and more like stand-alone data (which I often refer to in multiple notes). Would it be possible to add file type exclusion for this plugin?
Thank you for your work either way!

**Comment by JYC333** [comment]
Thanks for using this extension! It's added in 1.7.0 now.
