### ISSUE TITLE
Activate plugin manually

### ISSUE THREAD

**Issue by austingovella** [JYC333/obsidian-attachment-name-formatting#18]
Can you add a setting to allow the plugin to be triggered manually, instead of automatically?

If you use an image in more than one note, it renames the image each time you open up each note even though the image does not and probably should not be renamed.

**Comment by JYC333** [comment]
Hi, thanks for using the plugin!

The setting that turn off the auto-renaming is added in 1.8.0. And the problem you mention is related to [this issue](https://github.com/JYC333/obsidian-attachment-name-formatting/issues/5), plan to use symlink for an attachment that is used in multiple notes. Still working on it right now.
