### ISSUE TITLE
This plugin donot  format  attachments in the excalidraw file

### ISSUE THREAD

**Issue by trystudy** [JYC333/obsidian-attachment-name-formatting#19]
It cannot change the name of an image linked to a *.excalidraw file
Can you please confirm this?

**Comment by JYC333** [comment]
Hi, could you please give me some examples? I never use excalidraw.

**Comment by JYC333** [comment]
Just check with the excalidraw plugin, this plugin won't format the attachments in excalidraw file, since the excalidraw file doesn't use the standard obsidian md file structure.
