### ISSUE TITLE
[feature request] add an option to add ./ before attachment path

### ISSUE THREAD

**Issue by Castleeee** [JYC333/obsidian-attachment-name-formatting#2]
when paste images path is ![](static/xxx.png) which in other markdown renders is unsupported path.
if we can custom path prefix that will be great.

**Comment by Castleeee** [comment]
also in Obisdian , the " " will be replace to "%" which in other md render will cause error, I 'm not so familiar with Obisdian plugins developing ,so I only change the link charactor in main.js for my own use.
I hope it can be supported to define linker by users。

**Comment by JYC333** [comment]
Hi, thanks for using the plugin!
And sorry for the late reply, I'm restarting working on this now, will be back to you soon.

**Comment by JYC333** [comment]
Hi again, it has been delayed for quite a long time now... But now it's done.

Now you can open the option in the setting and copy the file path by right-clicking on the attachment link. Two options are provided, absolute and relative (according to the vault root).

**Comment by Castleeee** [comment]
Thanks for bringing Obsidian such a great plugin，have a nice day 😀
