### ISSUE TITLE
Allow / in names

### ISSUE THREAD

**Issue by android272** [JYC333/obsidian-attachment-name-formatting#20]
As a user, I would like to organize my attachments by file type, so that I can easily find them later by file type.

I installed this plugin, hoping that I would be able to name my images "images/2348980.png", video files "videos/2342345.wav", etc. like I have done with periodic notes. This way there would be subfolders in the Attachments folder.

**Comment by JYC333** [comment]
Is that mean you only want to add file type before the attachment string?

For example, you have a image attachment '2348980.png' in file 'some_file.md', you only want to rename it as 'images/2348980.png' under attachments folder.

Is that correct?

**Comment by android272** [comment]
No I was looking for an plugin that would sort types of attachments into folders under my attachments. As it is now Obsidian puts all attachments into a folder. I would like it so so that images would be place an images folder, videos in a videos folder, pdf in a documents folder.

In the periodic notes plugin you can choose a date format as the name of the file it creates when making a daily note for example. In that plugin you can add "/"s to also place your daily notes into sup folders. So I have my daily notes placed into my "Journal" folder, but because I set the file format to "YYYY/MM_MMM/YYYY-MM-DD" When I created todays daily note it placed the "2023-04-15" note into the "Journal/2023/04_Apr/" folder.

For this plugin I would like to make my image format "Images/1245.png" so that when I attach a png it would be placed into the "Attachments/Images" folder as apposed to just the "Attachments" folder.

Does that make sense?

**Comment by JYC333** [comment]
add in 1.9.4
