### ISSUE TITLE
Please add webp image format

### ISSUE THREAD

**Issue by heartnn** [JYC333/obsidian-attachment-name-formatting#21]
https://developers.google.com/speed/webp

some website use webp format to increase pages' speed

**Comment by JYC333** [comment]
Does obsidian support this format? From their official help document, it seems doesn't support `webp` format.

**Comment by heartnn** [comment]
https://help.obsidian.md/Advanced+topics/Accepted+file+formats

**Comment by JYC333** [comment]
add support in 1.9.3
