### ISSUE TITLE
Rescan Attachments in Current File always put renamed attachments at "assets" folder of root of vault

### ISSUE THREAD

**Issue by etca2z** [JYC333/obsidian-attachment-name-formatting#22]
I have Obsidian settings under "Files & Links" -> Default location for new attachments -> In subfolder under current folder.

When editing a file, invoke plugin command "Attachment Name Formatting: Rescan Attachments in Current File" from Obsidian Command Palette menu. The renamed attachments are relocated to "assets" folder under Vault root, instead of "assets" folder under the current folder.

Expected behaviour: the renamed attachments should move to location following the Obsidian settings under "Files & Links" -> Default location for new attachments".

**Comment by JYC333** [comment]
Thanks for reporting, should be fixed in 1.9.5.

If failed to rename some attachments, may need to re-insert the attachment into the note file.

**Comment by etca2z** [comment]
Sorry to say its not really fixed in 1.9.5 release.

When I set Obsidian settings under "Files & Links" -> Default location for new attachments -> In subfolder under current folder. When editing a file for example "Travel/France Food.md", with plug in "Automatic Formatting" turn off, when I add an image attachment let say IMG4588.png, Obsidian will place the image file into "Travel/assets/IMG4588.png".

So I would expect the plugin command "Attachment Name Formatting: Rescan Attachments in Current File" to rename the image and place under "Travel/assets/France Food_image_1.png".

For 1.9.5 when you invoke the command, the image file however is renamed to "assets/Travel/France Food_image_1.png", which is not in subfolder of current folder.

**Comment by JYC333** [comment]
Just checked again, I think should fix now. Please raise again if there is still some problems.
