### ISSUE TITLE
Feature Request: Seperate the two connectors

### ISSUE THREAD

**Issue by JosrJian** [JYC333/obsidian-attachment-name-formatting#25]
Between the file name and attachment name, we can set a connector, while there is no need to force the same connector between attachment name and the number. So I suggest we can seperate these two connectors and set them by ourselves.

![image](https://user-images.githubusercontent.com/61968860/234799274-cb2590e2-6b5e-496b-8392-ff2946f8d7c2.png)

As the image shows, the connector in the picture force the same connector between attachment name and number. I suggest we can set two options : one is connector between the file name and attachment name, another is connector between attachment name and the number. 

By the way , I hope the connector can be set none, which means I don't need any connector there. Thank you!

**Comment by JYC333** [comment]
It's added in 1.10.0 now.

**Comment by JosrJian** [comment]
> It's added in 1.10.0 now.

Yeah, it's OK Now we can set different connectors respectively. Thank you very much!

![image](https://user-images.githubusercontent.com/61968860/235291750-95fbc62c-c179-4faa-9453-eecc112a9a31.png)

As the image shows, the default connector is "_", while I hope the connector can also be set none, which means I don't need any connector there. Hope this can be added, too. Thanks a lot!

**Comment by JosrJian** [comment]
> It's added in 1.10.0 now.

Yeah, it's OK we can set different connectors respectively now. Thank you very much!

![image](https://user-images.githubusercontent.com/61968860/235291750-95fbc62c-c179-4faa-9453-eecc112a9a31.png)

As the image shows, the default connector is "_", while I hope the connector can also be set none, which means I don't need any connector there. I'm not sure whether this can be achieved. If it could, I hope this can be added, too. Thanks a lot!

**Comment by JYC333** [comment]
So you even don't want a space in between?

**Comment by JosrJian** [comment]
> So you even don't want a space in between?

Yeah, that's exactly what I really want to achieve.

**Comment by JYC333** [comment]
Hi, I have add this option in 2.0.0. But when you choose this option, it will disable some other options like #5.

**Comment by JosrJian** [comment]
Oh, thank you a lot for improving this plugin's function. I tried the new version.
I'll get no connectors if I choose none, but that's not exactly what I really want.
For example, I have a note named ''Note.md', then I hope the first image I paste can be renamed as 'Note_image1'. And for the second image, I hope it can be renamed as 'Note_image2' and so on... That's the reason why I hope I can choose 'none' as my connector, which doesn't mean I want **zero** connector actually.
I'm not sure whether this can be achieved but I hope so. Finally, thank you for the improvements to this plugin.

**Comment by JosrJian** [comment]
> Hi, I have add this option in 2.0.0. But when you choose this option, it will disable some other options like #5.

Oh, thank you a lot for improving this plugin's function. I tried the new version.
I'll get no connectors if I choose none, but that's not exactly what I really want.
For example, I have a note named ''Note.md', then I hope the first image I paste can be renamed as 'Note_image1'. And for the second image, I hope it can be renamed as 'Note_image2' and so on... That's the reason why I hope I can choose 'none' as my connector, which doesn't mean I want zero connector actually.
I'm not sure whether this can be achieved but I hope so. Finally, thank you for the improvements to this plugin.

**Comment by JYC333** [comment]
Hi, I update the strategy for the connector setting in 2.1.0 and this time will not have any limitations cooperate with the one-in-many options. Hope it fullfill your use case!

**Comment by JosrJian** [comment]
> Hi, I update the strategy for the connector setting in 2.1.0 and this time will not have any limitations cooperate with the one-in-many options. Hope it fullfill your use case!

Oh, thank you very much for fulfilling my personal needs, JYC! 
I tried it immediately and it does work well, which is just what I really want. This plugin truly helps me a lot in managing attachments. Thanks again for providing us such a nice tool!
