### ISSUE TITLE
[feature request] Add rescan option

### ISSUE THREAD

**Issue by waspeer** [JYC333/obsidian-attachment-name-formatting#3]
Hi! Love this plugin :) Thanks for working on this. I have an issue where sometimes when I insert an attachment the plugin does not pick up on it. I'm not seeing any issues in the console. Would it be possible to make a command that checks all the attachments in the note and renames them if still needed?

**Comment by JYC333** [comment]
Hi, thanks for using it! You can just modify the file with typing space to trigger the plugin at the moment.

I'll add a command later for the rescan.

**Comment by JYC333** [comment]
Hi again, sorry for the delay, the rescan command is added now!

**Comment by waspeer** [comment]
Thanks! :)
