### ISSUE TITLE
Bug when new attachment location is set to 'vault folder'

### ISSUE THREAD

**Issue by waspeer** [JYC333/obsidian-attachment-name-formatting#30]
Thanks for making this plugin!

I found an issue where the plugin crashes when the setting 'Default location for new attachments' is set to 'Vault folder'. I've set a breakpoint on the line I've linked below and `attachmentFolderPath` is undefined in this case, causing an error when trying to call `startsWith` on it.

https://github.com/JYC333/obsidian-attachment-name-formatting/blob/924e1db404015f7a4120623ca97f5616ffa4d600/src/main.ts#L357

**Comment by JYC333** [comment]
Hi, thanks for using it! And sorry for the late reply. It should be fixed in 2.1.1 now.
