### ISSUE TITLE
Error: Destination file already exists!

### ISSUE THREAD

**Issue by waspeer** [JYC333/obsidian-attachment-name-formatting#31]
Hi!

Thanks for making this plugin and maintaining it. I find it very useful!
I found a possible bug.

**How to reproduce:**
1. Make a note
2. Add an image (image will be renamed to eg. note_image_1.jpg)
3. Add a new image before the first image

This triggers an error for me: `Error: Destination file already exists!`

**My current workaround:**
1. Toggle on `Add modify time after index`
2. Run `Rescan attachments in current file`
3. Toggle off `Add modify time after index`
4. Run `Rescan attachments in current file` again

**Comment by JYC333** [comment]
Thanks for the bug report! I have fixed it in 2.1.2 now.
