### ISSUE TITLE
Add optional unqiue string in attachment name

### ISSUE THREAD

**Issue by sanjarcode** [JYC333/obsidian-attachment-name-formatting#32]
## Situation
My notes follow a rule:
1. Have a page (.md) for notes
2. Avoid having a page with the same name as a folder, especially on the same level, instead create an `index.md` in the folder. 

I have these rules since they make it navigate in a file explorer (reduces list size by half). And also for publishing the notes as a website.

## Problem
The current plugin format does not consider the route of the file (i.e. folder1/folder2/folder3). 
It only considers the `fileName` (`attachmentType` remains the same, and `indexNumber` may also be duplicated easily, so let's ignore them).

Due to my rule 2, all attachments in `index.md` files will be named the same - `index-image-indexNumber.xxx`.

## Solution
I know that the problem is specific to my situation,  and I think it's fine if the whole route is not in the attachment name (which would also solve the problem - but would make file names too big).

A simpler solution would be to have a unique identifier (by some logic - maybe hash the route) at the end of the filename. 
Storing "time" as the unique string doesn't help, since I also do linting (which edits multiple files quickly - at almost the same time).

**Comment by JYC333** [comment]
Thanks for creating pull request! Now it's added in 2.1.3
