### ISSUE TITLE
This plugin keeps updating the links of the uploaded images constantly, and I don't know what's going on.

### ISSUE THREAD

**Issue by FeiLZX3Km** [JYC333/obsidian-attachment-name-formatting#34]
![微信截图_20231207211653](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/21981195/85e01743-80bc-4b92-b69e-5fab5b9b0f3a)

**Comment by JYC333** [comment]
I'm not sure if it's the confliction of dataview plugin. I fix the confliction, and if there is still updating links constantly, please provide more information like the settings, related file structure.

**Comment by JYC333** [comment]
Closed since no updates for a quite a long time.
