### ISSUE TITLE
Bug: The connector can't be set "None"

### ISSUE THREAD

**Issue by JosrJian** [JYC333/obsidian-attachment-name-formatting#36]
When I set connectors in a note like the image below,
![Snipaste_2024-01-07_20-16-46](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/61968860/2eedbccc-e447-4f70-a580-9ea81e286497)
I get a 'Note_image_1.png' as return, which is not what I really want.
I hope the correct name is 'Note_image1.png'.

This problem is sloved in the past version, but it happened again when I updated in 2.1.8. I hope this can be solved, thank you!

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

It should fix in 2.1.9
