### ISSUE TITLE
"Scan files in folder" command isn't recursive?

### ISSUE THREAD

**Issue by VFansss** [JYC333/obsidian-attachment-name-formatting#38]
Hi!

First of all: thanks for your work, I appreciate the effort you put into this plugin: managing attachments is both important and a mess, and honestly this plugin seems to be my favourite one to manage attachments.

After installing it, everything works as intended. However, as you can imagine, I've already made hundred of attachments and I want to "normalize" them

![immagine](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/15073502/b1f98653-5f7b-4119-bea1-76c827f68365)

There's the option "Scan files in folder" but it acts weird:

- sometimes it doesn't actual get attachment within a file, so it doesn't move anything
- seems not to be recursive: if I select a parent folder (e.g. "Courses") where there are several notes or subfolders containing notes with attachments (e.g. "Courses/My Courses" with "Day 1 lecture notes.md", "Day 2 - other notes.md" etc) it doesn't move anything, albeit these notes are full of .png images
    - Isn't that option recursive?

**Comment by tyl0622** [comment]
I also encounter similar issues. When it comes to "Rescan Attachments in Current File", it works fine that attachments involved can be renamed. However, "Scan Files in the Folder" does not work after selecting a folder. I thought it would apply "Rescan" on every file in the folder, but it basically does nothing.

**Comment by Jackrabbitron** [comment]
Same here. I wonder if there is a way to trigger it by batch modifying multiple notes some other way?

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

Fix this error in 2.1.10 and add a new comand `Scan Files in the Folder (Recursive)`
