### ISSUE TITLE
Images/files disappearing or displaying incorrectly after file renames

### ISSUE THREAD

**Issue by stutopp** [JYC333/obsidian-attachment-name-formatting#39]
When I paste in new images, the rename process will sometimes lose images(i.e., the image gets tmp renamed and then fully renamed, but the link in the note still points to the tmp file). Other times, Obsidian live preview will display the wrong image and the read view will display the correct image. I can even link to the same image next to each other and it will display two different images.

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

Is this issue still happening? Could you please attach the logs or console output?

**Comment by stutopp** [comment]
I stopped using the plug-in because because of the issues.

Sorry for the close/open, not sure what happened there. Errant key-press, I assume.

**Comment by JYC333** [comment]
No worries, I can figure out this later.
