### ISSUE TITLE
Files are renamed to tmp_previousFileName after obsidian reload while using sync

### ISSUE THREAD

**Issue by artjafri** [JYC333/obsidian-attachment-name-formatting#4]
like the title says. files are renamed to "fileName image #" and then after a few hours I find the file has everything replaced with "tmp_FileName image #" breaking all the links.

**Comment by JYC333** [comment]
Hi, thanks for using this plugin! And sorry for the late reply.
I didn't use sync myself, so it's hard for me to reproduce this error. But I have some ideas that what may cause this problem, I'll check it and back to you. Sorry for the inconvience.

**Comment by JYC333** [comment]
Hi again, I have fixed the bug that probably may cause this problem. But since I didn't use sync, I couldn't reproduce the problem you have met. Hope the fix can also fix your problem.
