### ISSUE TITLE
Feature Request: Move all attachments of a file type to a subfolder named after the .md file

### ISSUE THREAD

**Issue by re4mat** [JYC333/obsidian-attachment-name-formatting#40]
I have a LOT of image attachments in my vault, and the `attachments/img/` folder that this plugin sends them all to has 919 files as of this writing. Having that many makes trying to find a particular file in either Obsidian's or the OS's file explorer rather unwieldy.

I propose that a feature be added (can be optional if you wish) that makes the plugin automatically create a subfolder _within_ the subfolder created by the "Subfolders for attachments" setting, named after the note that the attachment belongs to, and save all attachments into that sub-subfolder.

For example, if I'm working in a note (`foo.md`) and paste several images into the note, the plugin would rename the files as normal (e.g. `foo_image_1.png`), create a folder called `foo` within `attachments/img/`, and move all the attachments for `foo.md` (of the file type that belongs to that subfolder, in this case images) into `attachments/img/foo/`.

In the case of my vault, rather than scrolling through 919 images to find the right one, I would instead only need to scroll through 112 folders to find the attachments for the note that I'm looking for. Much more manageable!

Thank you for making such a great plugin! :)

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

This feature is added in 2.2.0 now.
