### ISSUE TITLE
Feature request: Add support for files formats .. TXT, ZIP, DOC, DOCX, XLS, XLSX, RTF, PPT, PTTX..

### ISSUE THREAD

**Issue by itoldusoandso** [JYC333/obsidian-attachment-name-formatting#43]
Support for a few more common office type files formats .. TXT, ZIP, DOC, DOCX, XLS, XLSX, RTF, PPT, PTTX

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

I add the custom attachment types support in 2.2.0, now you can set whatever formats you want with it.
