### ISSUE TITLE
Plugin not working if attachment folder has subfolders e.g. Vault / Folder / attachments / NoteName / ..... (rename attachment will not work)

### ISSUE THREAD

**Issue by itoldusoandso** [JYC333/obsidian-attachment-name-formatting#44]
Thank you for putting the effort in this plugin.

Unfortunately, the plugin doesn't work if I have attachments here:

**Vault / Folder / attachments / NoteName / .....** 

I tried the configure the in Obsidian Settings / Files and links ...  field Subfolder name to this:

_resources/${notename}

Doesn't help and the plugin can not accept it, so it doesn't work.  
I need to rename attachments to match the note name + index suffix. 

![image](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/71971273/26a8decf-dfcb-4ed5-b8af-34df98066ea9)

 It only works if I run this plugin for a specific folder only (I have to specifically select the subfolder with attachment). The issue with this (aside of the fact I have to repeat this 1000's of times) is when this plugin is executed on the specific folder, then the the plugin will overwrite the Obsidian Setting in Files and links .. field Subfolder with this entry:
 
 
![image](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/71971273/3fa5d28e-007b-4cbe-84a6-ed8ea976364e)

The next time I try execute the plugin on another folder, it doesn't run anymore correctly because now the Subfolder is pointed into the specific subfolder.

The way to solve this issue is for the plugin to support the variable notename so I can indicate the attachments are here: _resources/${notename}

Since the Obsidian setting in Files and links does not support notename variable, this setting will need to be as an **override** option inside this plugin.

The plugin is now designed to only run if the attachments are directly in the attachments folder e.g. Vault / Folder / attachments .....

I am using Attachment Manager to move attachments into subfolders as soon as attachments are added into the note.

So I hope if the plugin here can be modified to allow supporting Vault / Folder / attachments / NoteName / ..... 

![image](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/71971273/b69e2fee-9c04-4dc9-9e39-2ce31e5ec69f)

**Comment by 3fok** [comment]
In my case I waint the folder like this:
![image](https://github.com/JYC333/obsidian-attachment-name-formatting/assets/62346540/05ed20f6-242f-479b-8acd-ddab652e8ae9)

How to do it:
- Clone source code
- Change file src/main.ts line 385 to:
`let parent_path = path.join(
	'assets',
	file.parent.path,
	file.basename
);`
- `npm i` to install dependencies
- `npm run build` to start compilation in watch mode.
- Copy the `main.js`, `manifest.json` files to your vault `VaultFolder.obsidian/plugins/obsidian-attachment-name-formatting`
- Reload the plugin.
- Enjoy the magic :3

**Comment by itoldusoandso** [comment]
So right out of the bat, I throw in the commands in the terminal on MacOS?

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

This feature is added in 2.2.0 now, but it is setting from plugin not by using variable in Obsidian Setting in Files and links.
