### ISSUE TITLE
Attachment Name Formatting: Rescan Attachments in Current File

### ISSUE THREAD

**Issue by chenxin0397** [JYC333/obsidian-attachment-name-formatting#7]
The attachment renaming feature seems to only work for wiki links, using eg [[filename]] and such Wiki links.
Standard Markdown hyperlink syntax is used by default, such as ()[] is invalid

In addition, the ability to export attachments that are not linked in the library is also limited
If there is a vault in the vault, all attachments in the inner vault will be exported

**Comment by chenxin0397** [comment]
I tried it again just now, the dm link can be renamed, but the
![](../900-tools/zzz-resources/Pasted%20image%2020210815102332.png)
change to
![](Pasted%20image%2020210815102332.png)
to take effect

**Comment by JYC333** [comment]
Hi, thanks for using this plugin, and sorry for the late reply!

I have tested the Standard Markdown hyperlink syntax and it works for me, could you please provide some examples?

For the attachments, I use the function provided by Obsidian API to fetch all the attachments in the vault. It should only get the attachments related to the vault itself. By the way, I think it's no need to build a vault inside a vault, it sounds not a good idea.

And I couldn't get what you mean in your comment, could you explain it? Thanks!
